/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/** 
 *
 * @author GERARDO
 */
public class FrmSeguimientoClientes extends javax.swing.JFrame {

    /**
     * Creates new form FrmSeguimientoClientes
     */
    public FrmSeguimientoClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        LabelFechaAcuerdo1 = new javax.swing.JLabel();
        txtAcuerdo1 = new javax.swing.JTextField();
        txtFechaAcuerdo1 = new javax.swing.JTextField();
        LabelFechaAcuerdo2 = new javax.swing.JLabel();
        LabelAcuerdo1 = new javax.swing.JLabel();
        LabelAcuerdo2 = new javax.swing.JLabel();
        LabelFechaAcuerrdo3 = new javax.swing.JLabel();
        LabelAcuerdo4 = new javax.swing.JLabel();
        LabelAcuerdo3 = new javax.swing.JLabel();
        LabelFechaAcuerdo4 = new javax.swing.JLabel();
        txtFechaAcuerdo2 = new javax.swing.JTextField();
        txtAcuerdo2 = new javax.swing.JTextField();
        txtFechaAcuerdo4 = new javax.swing.JTextField();
        txtFechaAcuerdo3 = new javax.swing.JTextField();
        txtAcuerdo4 = new javax.swing.JTextField();
        txtAcuerdo3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ACUERDO_CUATRO");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ACUERDO_DOS");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("ACUERDO_TRES");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("remott");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("CEDULA");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("CIUDAD");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("DEPARTAMENTO");

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));

        jTextField5.setBackground(new java.awt.Color(204, 204, 255));

        jTextField6.setBackground(new java.awt.Color(204, 204, 255));

        jTextField7.setBackground(new java.awt.Color(204, 204, 255));

        LabelFechaAcuerdo1.setForeground(new java.awt.Color(204, 0, 204));
        LabelFechaAcuerdo1.setText("Fecha Acuerdo 1");

        txtAcuerdo1.setBackground(new java.awt.Color(255, 255, 255));
        txtAcuerdo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcuerdo1ActionPerformed(evt);
            }
        });

        txtFechaAcuerdo1.setBackground(new java.awt.Color(255, 255, 255));

        LabelFechaAcuerdo2.setForeground(new java.awt.Color(204, 0, 204));
        LabelFechaAcuerdo2.setText("Fecha de Acuerdo 2");

        LabelAcuerdo1.setForeground(new java.awt.Color(204, 0, 204));
        LabelAcuerdo1.setText("Acuerdo 1");

        LabelAcuerdo2.setForeground(new java.awt.Color(204, 0, 204));
        LabelAcuerdo2.setText("Acuerdo 2");

        LabelFechaAcuerrdo3.setForeground(new java.awt.Color(204, 0, 204));
        LabelFechaAcuerrdo3.setText("Fecha Acuerdo 3");

        LabelAcuerdo4.setForeground(new java.awt.Color(204, 0, 204));
        LabelAcuerdo4.setText("Acuerdo 4");

        LabelAcuerdo3.setForeground(new java.awt.Color(204, 0, 204));
        LabelAcuerdo3.setText("Acuerdo 3");

        LabelFechaAcuerdo4.setForeground(new java.awt.Color(204, 0, 204));
        LabelFechaAcuerdo4.setText("Fecha Acuerdo 4");

        txtFechaAcuerdo2.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaAcuerdo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAcuerdo2ActionPerformed(evt);
            }
        });

        txtAcuerdo2.setBackground(new java.awt.Color(255, 255, 255));
        txtAcuerdo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcuerdo2ActionPerformed(evt);
            }
        });

        txtFechaAcuerdo4.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaAcuerdo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAcuerdo4ActionPerformed(evt);
            }
        });

        txtFechaAcuerdo3.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaAcuerdo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAcuerdo3ActionPerformed(evt);
            }
        });

        txtAcuerdo4.setBackground(new java.awt.Color(255, 255, 255));
        txtAcuerdo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcuerdo4ActionPerformed(evt);
            }
        });

        txtAcuerdo3.setBackground(new java.awt.Color(255, 255, 255));
        txtAcuerdo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcuerdo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelAcuerdo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(LabelFechaAcuerdo1)
                    .addComponent(LabelAcuerdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFechaAcuerdo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelAcuerdo2)
                    .addComponent(LabelFechaAcuerdo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelFechaAcuerrdo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelAcuerdo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaAcuerdo4)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(jTextField4)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAcuerdo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFechaAcuerdo1)
                    .addComponent(txtFechaAcuerdo2)
                    .addComponent(txtAcuerdo2)
                    .addComponent(txtFechaAcuerdo3)
                    .addComponent(txtAcuerdo3)
                    .addComponent(txtAcuerdo4))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFechaAcuerdo1)
                    .addComponent(txtFechaAcuerdo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAcuerdo1)
                    .addComponent(LabelAcuerdo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFechaAcuerdo2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaAcuerdo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAcuerdo2)
                    .addComponent(txtAcuerdo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFechaAcuerrdo3)
                    .addComponent(txtFechaAcuerdo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAcuerdo3)
                    .addComponent(txtAcuerdo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFechaAcuerdo4)
                    .addComponent(txtFechaAcuerdo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAcuerdo4)
                    .addComponent(txtAcuerdo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcuerdo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcuerdo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcuerdo1ActionPerformed

    private void txtFechaAcuerdo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAcuerdo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAcuerdo2ActionPerformed

    private void txtAcuerdo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcuerdo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcuerdo2ActionPerformed

    private void txtFechaAcuerdo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAcuerdo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAcuerdo4ActionPerformed

    private void txtFechaAcuerdo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAcuerdo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAcuerdo3ActionPerformed

    private void txtAcuerdo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcuerdo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcuerdo4ActionPerformed

    private void txtAcuerdo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcuerdo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcuerdo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeguimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeguimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeguimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeguimientoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeguimientoClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAcuerdo1;
    private javax.swing.JLabel LabelAcuerdo2;
    private javax.swing.JLabel LabelAcuerdo3;
    private javax.swing.JLabel LabelAcuerdo4;
    private javax.swing.JLabel LabelFechaAcuerdo1;
    private javax.swing.JLabel LabelFechaAcuerdo2;
    private javax.swing.JLabel LabelFechaAcuerdo4;
    private javax.swing.JLabel LabelFechaAcuerrdo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField txtAcuerdo1;
    public javax.swing.JTextField txtAcuerdo2;
    public javax.swing.JTextField txtAcuerdo3;
    public javax.swing.JTextField txtAcuerdo4;
    public javax.swing.JTextField txtFechaAcuerdo1;
    public javax.swing.JTextField txtFechaAcuerdo2;
    public javax.swing.JTextField txtFechaAcuerdo3;
    public javax.swing.JTextField txtFechaAcuerdo4;
    // End of variables declaration//GEN-END:variables
}
